version: "3.3"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: apple_store
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: fastapi_backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"

  bot:
    build: ./bot
    container_name: telegram_bot
    restart: always
    depends_on:
      - backend
    env_file:
      - .env

  admin:
    build: ./admin
    container_name: react_admin
    restart: always
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8000
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    depends_on:
      - backend
      - admin
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

volumes:
  postgres_data:
